### ISSUE TITLE
Language not save

### ISSUE THREAD

**Issue by sakarya1980** [LittleTurtle2333/android_device_xiaomi_umi-twrp#3]
When i Change the language, reset it when i reboot to recovery again

**Comment by LittleTurtle2333** [comment]
Because the data is stored in data and cannot be decrypted, it cannot be saved.

**Comment by jeka57** [comment]
Is there any possibility to create a config file and put it in data partition using loaded rom in this case?

**Comment by Luffitys** [comment]
And on what partition would that config file be saved in? Stop this nonsense please
