### ISSUE TITLE
data is not decrypted

### ISSUE THREAD

**Issue by sakarya1980** [LittleTurtle2333/android_device_xiaomi_umi-twrp#4]
On Miui 12.2.2

**Comment by LittleTurtle2333** [comment]
Where did 12.2.2 come from?

**Comment by sakarya1980** [comment]
Miuimix stable 
![Uploading Screenshot_2020-11-16-06-01-21-736_com.android.settings.jpg…]()

**Comment by LittleTurtle2333** [comment]
![image](https://user-images.githubusercontent.com/32336368/99335547-0eab4480-28bc-11eb-91b6-9681dcaa3742.png)

**Comment by jeka57** [comment]
Hi! Thanks for the twrp modification for android 11! 
One question. What does it mean "Decryption (not supported by Android 11)" - it's impossible to decrypt data at all? Never? Or developers need some more time to fix this?

**Comment by Luffitys** [comment]
It means that TWRP sources aren't adapted to Android 11 yet, so until that's the case, there probably won't be any TWRP update that supports this /data decryption. Now stop reviving this closed issue
