### ISSUE TITLE
Xiaomi Mi 10 UMI - Internal storage decrypt does not work.

### ISSUE THREAD

**Issue by Merwenus** [LittleTurtle2333/android_device_xiaomi_umi-twrp#6]
As title says, after updating to latest xiaomi.eu rom it updated TWRP to this version and storage decrytption stopped working.
I don't have OTG pendrive, and now I can't install magisk.

**Comment by Luffitys** [comment]
The issue is known and is an official TWRP issue, therefore it will not be solved here. Either you will live without Magisk or you will have to buy yourself an OTG adapter.

**Comment by wSedlacek** [comment]
I'm interested in seeing this fixed as well, but I understand this may not be the place to track it. Where should it be tracked through?

Is there an upstream TWRP repo or something?

**Comment by Luffitys** [comment]
TWRP did not release a Android 11 TWRP branch yet, so until it's available there won't be any fixes.

**Comment by wSedlacek** [comment]
> TWRP did not release a Android 11 TWRP branch yet, so until it's available there won't be any fixes.

I believe this is the proper [repo](https://github.com/TeamWin/android_bootable_recovery)

@Merwenus can you make a issue here for Android 11 support?

@Luffitys @LittleTurtle2333 also I do believe an issue should remain here linked to the upstream issue simply so it can be tracked. I do understand that the responsibility of the issue may not be held here but it doesn't mean the issue doesn't exist and when it is fixed upstream there will need to be merges here to resolve the issue.

**Comment by Luffitys** [comment]
Yes, that repo is the correct one. There is however no reason for @Merwenus to create another issue, as this one is still kept open (unless OP closes it)

**Comment by wSedlacek** [comment]
> Yes, that repo is the correct one. There is however no reason for @Merwenus to create another issue, as this one is still kept open (unless OP closes it)

Let me clarify, I would like him to create an issue at [TeamWin/android_bootable_recovery](https://github.com/TeamWin/android_bootable_recovery)as I do not see an issue for Android 11 support there yet.

**Comment by Luffitys** [comment]
It is an officially known issue already (knowing it from certain sources). There is no further action required.

**Comment by wSedlacek** [comment]
> It is an officially known issue already (knowing it from certain sources). There is no further action required.

Can I get a reference for this? I was not able to find an issue open nor closed on the TeamWin repo nor was I able to find any resources outside of hearsay on forms via a Google search.

**Comment by Luffitys** [comment]
I am not sharing private messages, sorry.

**Comment by wSedlacek** [comment]
> I am not sharing private messages, sorry.

😅 Private messages isn't a great way to track issues for open source projects imho. I'll just go ahead and create a issue on the TeamWin repo myself so it can openly tracked.

**Comment by wSedlacek** [comment]
Has this issue been resolved?

**Comment by LittleTurtle2333** [comment]
> Has this issue been resolved?

Unresolvable

**Comment by wSedlacek** [comment]
> > Has this issue been resolved?
> 
> Unresolvable

Can we leave the issue open then?

I understand that there is a chain of responsibility that goes in with projects like this but it's important that those using this recovery understand it's limitations and the single best way to surface those limitations is via issues.

Beyond that having the issue surfaced may also lead to another developer gaining interest and finding a solution that we haven't thought of before.

**Comment by Luffitys** [comment]
No developer can fix anything without having access to the private twrp-11 branch. I can assure you that any Dev with access to it is already aware of the decryption issue.

**Comment by wSedlacek** [comment]
> No developer can fix anything without having access to the private twrp-11 branch. I can assure you that any Dev with access to it is already aware of the decryption issue.

[TWRP is protected under the GPL.](https://github.com/TeamWin/android_bootable_recovery/blob/android-10.0/NOTICE) It is against this license to modify the source code without releasing it.

>  To protect your rights, we need to prevent others from denying you
> these rights or asking you to surrender the rights.  Therefore, you have
> certain responsibilities if you distribute copies of the software, or if
> you modify it: responsibilities to respect the freedom of others.
> 
>  For example, if you distribute copies of such a program, whether
> gratis or for a fee, you must pass on to the recipients the same
> freedoms that you received.  You must make sure that they, too, receive
> or can get the source code.  And you must show them these terms so they
> know their rights.

Therefor if an Android 11 branch does exist it must be made public. Therefor my assertion that another developer could fix the issue would be true assuming that TWRP is playing by the GPL rules. If they are not playing by the GPL rules then there is a much bigger problem that needs to be addressed.
